#!/bin/sh

# prevent screen from blanking
xset s off -dpms

# disable mouse acceleration
xinput set-prop 8 "libinput Accel Profile Enabled" 0 1 0

# activate numlock
numlockx

# load resource file
xrdb -merge ~/.Xresources

# set background
xsetroot -solid "#442c2f"

# status bar
bar &

exec dwm
