#!/bin/sh

# disable dpms and prevent screen from blanking
xset s off -dpms &

# activate numlock
numlockx &

# notifications
dunst &

# statusbar script
bar &

# wallpaper
xsetroot -fg "#442c2f" -bg "#221000" -mod 2 2 &

# load resources
xrdb -merge ~/.Xresources

exec dwm
