#!/bin/sh

# disable dpms and prevent screen from blanking
xset s off -dpms &

# activate numlock
numlockx &

# notifications
dunst &

# statusbar script
bar &

# wallpaper
xsetroot -solid "#442c2f" &

# load resources
xrdb -merge ~/.Xresources

exec dwm
