#!/bin/sh

# dpi
xrandr --dpi 96 &

# keyboard layout
setxkbmap -layout us,ru -option grp:rctrl_toggle,grp_led:scroll,ctrl:nocaps,compose:menu &

# adjust typematic delay and rate
xset r rate 300 50 &

# disable dpms and prevent screen from blanking
xset s off -dpms &

# activate numlock
numlockx &

# statusbar script
baraction.sh &

exec dwm
