window:
  dimensions:
    columns: 80
    lines: 24
  padding:
    x: 2
    y: 2
  decorations: none
  dynamic_padding: true

font:
  normal:
    family: Go Mono
  size: 10.5

mouse:
  hide_when_typing: true
