window:
  dimensions:
    columns: 167
    lines: 48
  padding:
    x: 8
    y: 8
  decorations: none
  dynamic_padding: true

font:
  normal:
    family: Go Mono
  size: 10.5

mouse:
  hide_when_typing: true
