window:
  dimensions:
    columns: 167
    lines: 48
  padding:
    x: 8
    y: 8
  decorations: none
  dynamic_padding: true

font:
  normal:
    family: Go Mono
  size: 10.5

mouse:
  hide_when_typing: true

# Alduin colorscheme
# colors:
#   primary:
#     background: '#1c1c1c'
#     foreground: '#dfdfaf'
#   normal:
#     black:   '#1c1c1c'
#     red:     '#af5f5f'
#     green:   '#87875f'
#     yellow:  '#af875f'
#     blue:    '#878787'
#     magenta: '#af8787'
#     cyan:    '#87afaf'
#     white:   '#dfdfaf'
#   bright:
#     black:   '#878787'
#     red:     '#af5f5f'
#     green:   '#87875f'
#     yellow:  '#af875f'
#     blue:    '#878787'
#     magenta: '#af8787'
#     cyan:    '#87afaf'
#     white:   '#dfdfaf'

# Parchment colorscheme
colors:
  primary:
    background: '#ffffea'
    foreground: '#000000'
  normal:
    black:   '#000000'
    red:     '#880000'
    green:   '#005500'
    yellow:  '#663311'
    blue:    '#004488'
    magenta: '#770077'
    cyan:    '#007777'
    white:   '#eeeecc'
  bright:
    black:   '#eaeaea'
    red:     '#ffeaea'
    green:   '#eaffea'
    yellow:  '#eeee9e'
    blue:    '#cceeff'
    magenta: '#ffeaff'
    cyan:    '#eaffff'
    white:   '#ffffea'
