window:
  dimensions:
    columns: 167
    lines: 48
  padding:
    x: 8
    y: 8
  decorations: none
  dynamic_padding: true

font:
  normal:
    family: Fantasque Sans Mono
  size: 12.0

mouse:
  hide_when_typing: true

colors:
  primary:
    background: '#1c1c1c'
    foreground: '#dfdfaf'
  normal:
    black:   '#1c1c1c'
    red:     '#af5f5f'
    green:   '#87875f'
    yellow:  '#af875f'
    blue:    '#878787'
    magenta: '#af8787'
    cyan:    '#87afaf'
    white:   '#dfdfaf'
  bright:
    black:   '#878787'
    red:     '#af5f5f'
    green:   '#87875f'
    yellow:  '#af875f'
    blue:    '#878787'
    magenta: '#af8787'
    cyan:    '#87afaf'
    white:   '#dfdfaf'
